/**
 * Default exercise library — seeded for new users on first load.
 * Written in the NEW canonical format (category = muscle group, movementPattern = biomechanics).
 * Equipment is NEVER included in the name — the equipment field handles that.
 * isFavourite and ytSearch default to false / '' — storage migration fills them in.
 */

/**
 * IDs that were previously in DEFAULT_EXERCISES but have been removed (de-duplicated or superseded).
 * seedDefaultExercises() will purge these from localStorage so they don't linger for existing users.
 */
export const RETIRED_EXERCISE_IDS = ['e72', 'e73', 'e77', 'e78', 'e79']

const DEFAULT_EXERCISES = [
  // ── CHEST ──
  {id:'e1',  name:'Push-ups',              category:'chest',     movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:60,  muscles:'Chest, triceps, front delts, core',        notes:'Hands shoulder-width, elbows at 45 degrees. Lower chest to floor, full lockout at top. Brace core throughout; no sagging hips.'},
  {id:'e15', name:'Wide Push-ups',         category:'chest',     movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Outer chest, front delts, triceps',         notes:'Hands wider than shoulder-width, fingers pointing slightly outward. Elbows flare more than standard push-ups.'},
  {id:'e16', name:'Decline Push-ups',      category:'chest',     movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Upper chest, front delts, triceps',         notes:'Feet elevated on a chair. Shifts emphasis to upper chest and shoulders. Higher feet = harder.'},
  {id:'e6',  name:'Chest Press',           category:'chest',     movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Chest, front delts, triceps',               notes:'Lie on a bench or floor. Press up and slightly in. Lower slowly with control. Squeeze chest at the top.'},
  {id:'e34', name:'Chest Flyes',           category:'chest',     movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Chest (stretch emphasis), front delts',     notes:'Arms wide with slight elbow bend throughout. Lower until deep chest stretch, arc back up. Go lighter than you think.'},


  // ── BACK ──
  {id:'e5',  name:'Bent Over Row',         category:'back',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Lats, rhomboids, rear delts, biceps',       notes:'One hand and knee on bench. Pull to hip — lead with elbow not hand. Neutral spine throughout.'},
  {id:'e45', name:'Chest Supported Row',   category:'back',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Lats, rhomboids, rear delts, biceps',       notes:'Lie chest-down on incline bench. Row elbows back toward hips. Removes all lower back strain.'},
  {id:'e75', name:'Seated Row',            category:'back',      movementPattern:'pull',      equipment:'cable',   defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Lats, rhomboids, rear delts, biceps',       notes:'Neutral grip, sit upright. Pull to lower chest, elbows close to body. Squeeze shoulder blades at the end. Do not rock back. Full stretch at the start.'},
  {id:'e8',  name:'Scapula Pulls',         category:'back',      movementPattern:'pull',      equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Serratus anterior, lower traps',            notes:'Hang with straight arms. Depress and retract shoulder blades without bending elbows. Body rises slightly.'},
  {id:'e10', name:'Assisted Pull-ups',     category:'back',      movementPattern:'pull',      equipment:'bw',      defaultSets:3, defaultReps:5,  defaultRest:90,  muscles:'Lats, biceps, rear delts, core',            notes:'Use a resistance band or chair for assistance. Same form as full pull-ups. Progressively reduce assistance.'},
  {id:'e46', name:'Pull-ups',              category:'back',      movementPattern:'pull',      equipment:'bw',      defaultSets:3, defaultReps:6,  defaultRest:90,  muscles:'Lats, biceps, rear delts, core',            notes:'Overhand grip, dead hang start. Pull until chin clears bar. No kipping. Lower slowly — 3 seconds down.'},
  {id:'e47', name:'Chin-ups',              category:'back',      movementPattern:'pull',      equipment:'bw',      defaultSets:3, defaultReps:6,  defaultRest:90,  muscles:'Biceps, lats, rear delts',                  notes:'Underhand grip, shoulder-width. More bicep than pull-ups. Dead hang start, chin over bar, slow descent.'},
  {id:'e48', name:'Dead Hang',             category:'back',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, trackingType:'time', defaultDuration:30, defaultRest:60, muscles:'Grip, forearms, shoulder decompression',    notes:'Hang with straight arms. Actively pack the shoulders rather than fully passive hanging. Build toward 60 second hangs.'},
  {id:'e51', name:'Inverted Rows',         category:'back',      movementPattern:'pull',      equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Lats, rhomboids, rear delts, biceps',       notes:'Lie under table or low bar. Pull chest up to bar. More horizontal = harder. Feet elevated = harder.'},
  {id:'e52', name:'Rows',                  category:'back',      movementPattern:'pull',      equipment:'band',    defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Lats, rhomboids, rear delts, biceps',       notes:'Anchor band at waist height. Row elbows back past your sides, pause and squeeze. Keep torso still.'},
  {id:'e74', name:'Lat Pulldown',          category:'back',      movementPattern:'pull',      equipment:'machine', defaultSets:3, defaultReps:10, defaultRest:75,  muscles:'Lats, biceps, rear delts',                  notes:'Wide overhand grip. Pull bar to upper chest, lead with elbows. Lean back slightly. Squeeze lats at the bottom. Control the return — do not let the weight yank you up.'},
  {id:'e76', name:'Pullover',              category:'back',      movementPattern:'pull',      equipment:'cable',   defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Lats, teres major, chest (lower)',          notes:'Cable set high. Straight arms, pull cable down and back in a wide arc to hips. Pure lat isolation with constant tension. Great finisher for back sessions.'},
  {id:'e29', name:'Superman Hold',         category:'back',      movementPattern:'hinge',     equipment:'bw',      defaultSets:3, trackingType:'time', defaultDuration:10, defaultRest:30, muscles:'Lower back, glutes, rear delts',            notes:'Lift arms, chest and legs simultaneously. Squeeze glutes. Works entire posterior chain.'},

  // ── SHOULDERS ──
  {id:'e17', name:'Pike Push-ups',         category:'shoulders', movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Shoulders, triceps, upper traps',           notes:'Inverted V position, hips high. Lower head toward floor between hands. Feet elevated = harder.'},
  {id:'e31', name:'Shoulder Press',        category:'shoulders', movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Shoulders, triceps, upper traps',           notes:'Start at ear height, elbows at 90 degrees. Press overhead. Lower slowly. Keep ribs down.'},
  {id:'e43', name:'Arnold Press',          category:'shoulders', movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'All three delt heads, triceps',             notes:'Start palms facing you. Rotate outward as you press overhead. Reverse on the way down.'},
  {id:'e32', name:'Lateral Raise',         category:'shoulders', movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Side delts, upper traps',                   notes:'Raise to shoulder height, pinky slightly higher than thumb. Lower slowly. Do not shrug.'},

  {id:'e33', name:'Front Raise',           category:'shoulders', movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Front delts, upper chest',                  notes:'Raise to shoulder height, arms nearly straight. Do not rock torso. Lower slowly.'},
  {id:'e42', name:'Rear Delt Fly',         category:'shoulders', movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Rear delts, rhomboids, mid traps',          notes:'Hinge forward, back flat. Raise arms to sides in wide arc — elbows going up. Go light.'},
  {id:'e44', name:'Shrugs',                category:'shoulders', movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Upper traps, levator scapulae',             notes:'Elevate shoulders straight up toward ears — no rolling. Hold briefly at top. Lower slowly.'},
  {id:'e9',  name:'W-Pulls',               category:'shoulders', movementPattern:'pull',      equipment:'band',    defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Rear delts, external rotators, mid traps',  notes:'Pull hands apart forming a W — elbows bent, hands by ears, palms forward. Key is external rotation at top.'},
  {id:'e49', name:'Pull-Aparts',           category:'shoulders', movementPattern:'pull',      equipment:'band',    defaultSets:3, defaultReps:15, defaultRest:30,  muscles:'Rear delts, rhomboids, external rotators',  notes:'Arms straight at shoulder height. Pull apart, squeezing shoulder blades. Keep arms straight throughout.'},
  {id:'e50', name:'Face Pulls',            category:'shoulders', movementPattern:'pull',      equipment:'band',    defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Rear delts, external rotators, mid traps',  notes:'Pull toward face, hands finishing by ears — elbows high. Hands finish higher than elbows.'},
  {id:'e53', name:'Shoulder Dislocates',   category:'shoulders', movementPattern:null,        equipment:'band',    defaultSets:2, defaultReps:10, defaultRest:30,  muscles:'Shoulder capsule, pec minor, lats',         notes:'Wide grip on band. Arc overhead and behind until band reaches behind hips. Slowly work grip narrower.'},

  // ── ARMS ──
  {id:'e14', name:'Diamond Push-ups',      category:'arms',      movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Triceps, inner chest, front delts',         notes:'Hands form a diamond under chest. Elbows stay close to sides as you lower. More tricep than chest.'},
  {id:'e27', name:'Tricep Dips',           category:'arms',      movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Triceps, front delts, chest',               notes:'Use a sturdy chair. Hands gripping edge, fingers forward. Lower until elbows hit 90 degrees. Legs extended = harder.'},
  {id:'e40', name:'Skull Crushers',        category:'arms',      movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Triceps (all three heads)',                  notes:'Lower towards temples bending only at elbows. Upper arms stay vertical. Lower slowly.'},
  {id:'e41', name:'Tricep Kickbacks',      category:'arms',      movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Triceps (long head)',                        notes:'Hinge forward, upper arm parallel to floor. Extend forearm back to lockout, squeezing hard.'},
  {id:'e66', name:'Overhead Tricep Extension', category:'arms',  movementPattern:'push',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Triceps (long head)',                        notes:'Hold one dumbbell with both hands overhead, elbows pointing up. Lower behind your head, upper arms stay vertical. Full extension at top.'},
  {id:'e67', name:'Tricep Pushdown',       category:'arms',      movementPattern:'push',      equipment:'band',    defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Triceps (all three heads)',                  notes:'Anchor band overhead. Elbows pinned to sides. Push down to full extension, squeeze hard at lockout. Slow on the return.'},

  {id:'e7',  name:'Bicep Curls',           category:'arms',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Biceps, brachialis, forearms',               notes:'Elbows pinned to sides. Curl up, supinate wrist at top. Lower slowly over 2-3 seconds.'},

  {id:'e39', name:'Hammer Curls',          category:'arms',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Brachialis, biceps, forearms',               notes:'Neutral grip throughout — do not rotate wrist. Targets brachialis for arm thickness.'},
  {id:'e68', name:'Concentration Curl',    category:'arms',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:45,  muscles:'Biceps (peak)',                              notes:'Seated, elbow braced against inner thigh. Curl slowly, full range. Zero momentum — pure bicep. Best exercise for the bicep peak.'},
  {id:'e69', name:'Incline Curl',          category:'arms',      movementPattern:'pull',      equipment:'db',      defaultSets:3, defaultReps:10, defaultRest:45,  muscles:'Biceps (long head), brachialis',             notes:'Lie back on incline bench, arms hanging straight down. Curl up with supination. Incline pre-stretches the long head — more range than a standing curl.'},
  {id:'e70', name:'Wrist Curls',           category:'arms',      movementPattern:'isometric', equipment:'db',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Forearms, wrist flexors',                   notes:'Forearms resting on knees or bench, palms up. Curl wrists upward. Low weight, high reps. Essential for grip strength — relevant for climbers.'},
  {id:'e71', name:'Reverse Wrist Curls',   category:'arms',      movementPattern:'isometric', equipment:'db',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Forearms, wrist extensors',                  notes:'Same as wrist curls but palms facing down. Trains the extensor side of the forearm. Balances the flexors and prevents tennis elbow.'},

  // ── LEGS ──
  {id:'e2',  name:'Squats',                category:'legs',      movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:20, defaultRest:60,  muscles:'Quads, glutes, hamstrings, core',           notes:'Feet shoulder-width, toes slightly out. Sit back and down — chest up, knees over toes. Hit parallel or below.'},
  {id:'e18', name:'Lunges',                category:'legs',      movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Quads, glutes, hamstrings, core',           notes:'Step forward, lower until rear knee almost touches floor. Front shin stays vertical. Drive through front heel.'},
  {id:'e19', name:'Reverse Lunges',        category:'legs',      movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Quads, glutes, hamstrings',                 notes:'Step backward — easier on knees. Lower rear knee toward floor, front knee stays over ankle.'},
  {id:'e20', name:'Bulgarian Split Squat', category:'legs',      movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:75,  muscles:'Quads, glutes, hip flexors',                notes:'Rear foot elevated on chair. Front foot far enough forward so shin stays vertical at bottom.'},
  {id:'e21', name:'Step-ups',              category:'legs',      movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Quads, glutes, hamstrings',                 notes:'Drive through heel of working leg. Do not push off trailing foot. Full hip extension at top.'},
  {id:'e36', name:'Goblet Squat',          category:'legs',      movementPattern:'squat',     equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Quads, glutes, core, upper back',           notes:'Hold weight at chest. Squat deep — elbows inside knees at bottom. Great for learning squat mechanics.'},
  {id:'e37', name:'Sumo Squat',            category:'legs',      movementPattern:'squat',     equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Inner thighs, glutes, quads',               notes:'Wide stance, toes out 45 degrees. Hold one weight between legs. Knees push out over toes.'},
  {id:'e38', name:'Weighted Lunges',       category:'legs',      movementPattern:'squat',     equipment:'db',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Quads, glutes, hamstrings',                 notes:'Weights at sides. Front shin stays vertical, rear knee approaches floor. Start light.'},
  {id:'e23', name:'Hip Abduction',         category:'legs',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Glute medius, hip abductors',               notes:'Lie on side, hips stacked. Lift top leg to 45 degrees, toes slightly down. Slow and controlled.'},
  {id:'e35', name:'Romanian Deadlift',     category:'legs',      movementPattern:'hinge',     equipment:'db',      defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Hamstrings, glutes, lower back',            notes:'Push hips back lowering weights down legs. Feel strong hamstring stretch. Neutral spine is critical.'},
  {id:'e4',  name:'Glute Bridges',         category:'legs',      movementPattern:'hinge',     equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Glutes, hamstrings, lower back',            notes:'Drive hips up by squeezing glutes — not by arching lower back. Hold 2s at top. Lower slowly.'},
  {id:'e22', name:'Hip Thrust',            category:'legs',      movementPattern:'hinge',     equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Glutes, hamstrings, core',                  notes:'Upper back on sofa or bench. Drive hips up squeezing glutes — full extension. Chin tucked slightly.'},
  {id:'e80', name:'Leg Press',             category:'legs',      movementPattern:'squat',     equipment:'machine', defaultSets:3, defaultReps:12, defaultRest:90,  muscles:'Quads, glutes, hamstrings',                 notes:'Feet shoulder-width on platform. Lower until knees reach 90 degrees. Press through mid-foot. Foot higher = more glute; lower = more quad.'},
  {id:'e81', name:'Leg Extension',         category:'legs',      movementPattern:'squat',     equipment:'machine', defaultSets:3, defaultReps:15, defaultRest:60,  muscles:'Quadriceps (isolation)',                     notes:'Pad just above ankles. Extend to full lockout, hold briefly, lower slowly. The only exercise that directly isolates the quads.'},
  {id:'e82', name:'Leg Curl',              category:'legs',      movementPattern:'hinge',     equipment:'machine', defaultSets:3, defaultReps:12, defaultRest:60,  muscles:'Hamstrings (isolation)',                     notes:'Curl heels toward glutes through full range. Lower slowly — hamstring tears happen on the eccentric.'},
  {id:'e83', name:'Calf Press',            category:'legs',      movementPattern:'isometric', equipment:'machine', defaultSets:4, defaultReps:15, defaultRest:45,  muscles:'Gastrocnemius, soleus',                     notes:'Toes on lower edge of leg press platform. Full range — heels below toes at the bottom. Slow lower is key.'},

  // ── CORE ──
  {id:'e3',  name:'Plank',                 category:'core',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, trackingType:'time', defaultDuration:30, defaultRest:45, muscles:'Core, shoulders, glutes',                   notes:'Elbows under shoulders. Squeeze glutes, brace abs. Body forms a straight line.'},
  {id:'e30', name:'Side Plank',            category:'core',      movementPattern:'isometric', equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:20, defaultRest:30, muscles:'Obliques, glutes, shoulders',               notes:'Each side. Forearm on floor, elbow under shoulder. Hips stay up.'},
  {id:'e24', name:'Dead Bug',              category:'core',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:45,  muscles:'Core, hip flexors, lower back',             notes:'Arms up, knees at 90 degrees. Lower opposite arm and leg simultaneously. Lower back must stay flat.'},
  {id:'e25', name:'Bird Dog',              category:'core',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:45,  muscles:'Core, glutes, lower back',                  notes:'Extend opposite arm and leg, hold 2s, return without touching floor. Resist any hip rotation.'},
  {id:'e26', name:'Mountain Climbers',     category:'core',      movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Core, hip flexors, shoulders',              notes:'Plank position. Drive knees alternately toward chest. Hips stay level — do not let them bounce.'},
  {id:'e28', name:'Hollow Body Hold',      category:'core',      movementPattern:'isometric', equipment:'bw',      defaultSets:3, trackingType:'time', defaultDuration:20, defaultRest:45, muscles:'Core, hip flexors, lats',                   notes:'Press lower back into floor. Arms overhead, legs straight and raised. Everything braced.'},

  // ── MOBILITY ──
  {id:'e11', name:'Ankle Circles',         category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, defaultReps:20, defaultRest:30,  muscles:'Ankle joint, peroneals, tibialis',          notes:'Draw large circles with foot — clockwise and anticlockwise. 20 reps each direction.'},
  {id:'e12', name:'Calf Raises',           category:'mobility',  movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Gastrocnemius, soleus',                     notes:'Edge of step for full range. Rise onto tiptoes, lower slowly below step. Single leg = far more effective.'},
  {id:'e13', name:'Ankle Alphabet',        category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, defaultReps:1,  defaultRest:30,  muscles:'Ankle stabilisers, peroneals',              notes:'Reps = full alphabet. Seated, foot off floor. Write each letter with your big toe. Do both feet.'},
  {id:'e54', name:'Single Leg Calf Raise', category:'mobility',  movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Gastrocnemius, soleus, peroneals',          notes:'Balance on one foot. Rise slowly, lower over 3 seconds. Gold standard for Achilles rehab.'},
  {id:'e55', name:'Seated Calf Raise',     category:'mobility',  movementPattern:'isometric', equipment:'db',      defaultSets:3, defaultReps:20, defaultRest:30,  muscles:'Soleus (deep calf)',                        notes:'Weight on thighs, seated. Targets soleus rather than gastrocnemius. Important for Achilles health.'},
  {id:'e56', name:'Tibialis Raises',       category:'mobility',  movementPattern:'isometric', equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:30,  muscles:'Tibialis anterior (shin)',                  notes:'Lean against wall, heels 30cm out. Lift toes as high as possible. Prevents shin splints.'},
  {id:'e57', name:'Hip Flexor Stretch',    category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:30, defaultRest:20, muscles:'Iliopsoas, rectus femoris',                 notes:'Each side. Half-kneeling. Tuck pelvis under and drive hips gently forward.'},
  {id:'e58', name:"World's Greatest Stretch", category:'mobility', movementPattern:null,      equipment:'bw',      defaultSets:2, defaultReps:5,  defaultRest:30,  muscles:'Hip flexors, thoracic spine, adductors',    notes:'From lunge, place hand inside front foot. Rotate other arm toward ceiling. 5 reps per side.'},
  {id:'e59', name:'90/90 Hip Stretch',     category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:30, defaultRest:20, muscles:'Hip external and internal rotators, glutes', notes:'Both legs at 90 degrees. Sit upright and feel the stretch in both hips.'},
  {id:'e60', name:'Thoracic Rotation',     category:'mobility',  movementPattern:'rotation',  equipment:'bw',      defaultSets:2, defaultReps:10, defaultRest:20,  muscles:'Thoracic spine, obliques',                  notes:'Hand behind head, rotate elbow toward ceiling. Movement from mid-back. 10 each side.'},
  {id:'e61', name:'Cat-Cow',               category:'mobility',  movementPattern:'rotation',  equipment:'bw',      defaultSets:2, defaultReps:10, defaultRest:20,  muscles:'Spine, core, back extensors',               notes:'All fours. Round spine up (cat), drop belly toward floor (cow). Move slowly.'},
  {id:'e62', name:'Glute Stretch',         category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:30, defaultRest:20, muscles:'Glutes, piriformis, hip external rotators', notes:'Each side. Figure-4: cross ankle over opposite knee, pull both legs toward chest.'},
  {id:'e63', name:'Hamstring Stretch',     category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:30, defaultRest:20, muscles:'Hamstrings, posterior chain',               notes:'Each leg. Loop band around foot, straighten leg toward ceiling.'},
  {id:'e64', name:'Pec Stretch',           category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:30, defaultRest:20, muscles:'Pectorals, front delts',                    notes:'Forearm against doorframe at 90 degrees. Lean through gently.'},
  {id:'e65', name:'Lat Stretch',           category:'mobility',  movementPattern:null,        equipment:'bw',      defaultSets:2, trackingType:'time', defaultDuration:20, defaultRest:20, muscles:'Latissimus dorsi, teres major',             notes:'Each side. Reach overhead and hold something fixed. Lean away and rotate slightly.'},

  // ── CLIMBING / GRIP ──
  // Supplementary grip & finger strength work. Hangboard timer handles timed crimp hangs separately.
  {id:'e90', name:'Pinch Block Hold',          category:'arms', movementPattern:'isometric', equipment:'other', defaultSets:3, trackingType:'time', defaultDuration:15, defaultRest:90,  muscles:'Thumb, finger flexors, forearms',           notes:'Each side. Hold a pinch block or smooth-sided weight between thumb and fingers. Most climbers neglect the thumb — fix that here. Keep wrist neutral.'},
  {id:'e91', name:'Plate Pinch',               category:'arms', movementPattern:'isometric', equipment:'other', defaultSets:3, trackingType:'time', defaultDuration:20, defaultRest:90,  muscles:'Thumb, finger flexors, forearms',           notes:'Two weight plates back-to-back, smooth sides out. Pinch and hold at your side. Gym-accessible pinch training. Progress by adding a third plate.'},
  {id:'e92', name:'Rice Bucket',               category:'arms', movementPattern:'isometric', equipment:'other', defaultSets:3, trackingType:'time', defaultDuration:60, defaultRest:60,  muscles:'Finger extensors, flexors, forearms',       notes:'Plunge hand into bucket of rice. Open and close fingers slowly, rotate wrist. Excellent for both rehab and finger conditioning — trains extensors and flexors together.'},
  {id:'e93', name:'Towel Pull-ups',            category:'arms', movementPattern:'pull',      equipment:'bw',    defaultSets:3, defaultReps:5,  defaultRest:90,  muscles:'Grip, forearms, lats, biceps',              notes:'Drape two towels over a pull-up bar. Grip each towel and perform pull-ups. The unstable, thick surface massively increases grip demand. Progress to a single folded towel.'},
  {id:'e94', name:'Finger Extensions',         category:'arms', movementPattern:'push',      equipment:'band',  defaultSets:3, defaultReps:25, defaultRest:30,  muscles:'Finger extensors, forearm extensors',       notes:'Loop a theraband or rubber band around all four fingers. Open hand fully against resistance, close slowly. The single most important injury prevention exercise for climbers — do this every session.'},
  {id:'e95', name:'One Arm Dead Hang',         category:'arms', movementPattern:'isometric', equipment:'bw',    defaultSets:3, trackingType:'time', defaultDuration:10, defaultRest:120, muscles:'Grip, forearms, lats, shoulder stabilisers', notes:'Each arm. Use a doorframe or hangboard. Start with fingers of the free hand on your wrist for partial assistance. Build to unassisted hangs. Brutal on the shoulder — pack it actively.'},
  {id:'e96', name:'Finger Rolls',              category:'arms', movementPattern:'pull',      equipment:'db',    defaultSets:3, defaultReps:15, defaultRest:60,  muscles:'Finger flexors, forearms',                  notes:'Hold dumbbell with fingers only — not in the palm. Let it roll toward your fingertips under control, then curl back up. Direct finger flexor tendon strengthening. Go very light.'},
  {id:'e97', name:'Wrist Pronation/Supination',category:'arms', movementPattern:'isometric', equipment:'db',    defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Pronators, supinators, forearm rotators',   notes:'Hold dumbbell at one end, forearm resting on knee. Rotate palm down (pronation) then up (supination) through full range. Essential for medial epicondyle (climber\'s elbow) health.'},
  {id:'e98', name:'Crimp Block Pull',          category:'arms', movementPattern:'pull',      equipment:'other', defaultSets:4, defaultReps:5,  defaultRest:180, muscles:'Finger flexors, A2 pulley, forearms',       notes:'Load a crimp block (Transgression, Tension, Grasshopper etc.) on a loading pin. Crimp the edge and pull from the floor. Short reps, heavy weight, long rest — this is max strength work, not endurance. Warm up thoroughly.'},
  {id:'e99', name:'Open Hand Block Pull',      category:'arms', movementPattern:'pull',      equipment:'other', defaultSets:4, defaultReps:5,  defaultRest:180, muscles:'Finger flexors, forearms',                  notes:'Same as crimp block pull but use an open-hand position. Safer for tendons than full crimp. Load a block on a loading pin, pull from floor. Treat this like a 1RM lift — build weight weekly.'},
  {id:'e100',name:'Two Finger Block Pull',     category:'arms', movementPattern:'pull',      equipment:'other', defaultSets:3, defaultReps:5,  defaultRest:180, muscles:'Index+middle or middle+ring finger flexors', notes:'Two-finger pocket simulation. Middle+ring is the weaker but more commonly used pair — start there. Very light loads. Critical for overhanging pocket climbing. Never train this on cold tendons.'},
  {id:'e101',name:'Weighted Block Hang',       category:'arms', movementPattern:'isometric', equipment:'other', defaultSets:3, trackingType:'time', defaultDuration:10, defaultRest:180, muscles:'Finger flexors, A2 pulley, forearms',       notes:'Hang from a crimp block with added weight (belt or vest). Shorter duration than hangboard repeaters — this is max strength, aim for a load where 10s is very hard. Log the added weight per set.'},

  // ── CARDIO ──
  {id:'e84', name:'Burpees',               category:'cardio',    movementPattern:'push',      equipment:'bw',      defaultSets:3, defaultReps:10, defaultRest:60,  muscles:'Full body, cardiovascular',                 notes:'Jump down to plank, chest to floor, press up, jump feet to hands, jump up with arms overhead. Scale by stepping instead of jumping.'},
  {id:'e85', name:'Jumping Jacks',         category:'cardio',    movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:30, defaultRest:30,  muscles:'Full body, cardiovascular',                 notes:'Arms and legs go out simultaneously, then back together. Slight bend in knees on landing.'},
  {id:'e86', name:'High Knees',            category:'cardio',    movementPattern:'squat',     equipment:'bw',      defaultSets:3, trackingType:'time', defaultDuration:30, defaultRest:30, muscles:'Hip flexors, quads, cardiovascular',        notes:'Run on the spot, driving knees up to hip height. Pump arms as if running. Keep chest upright.'},
  {id:'e87', name:'Jump Squats',           category:'cardio',    movementPattern:'squat',     equipment:'bw',      defaultSets:3, defaultReps:15, defaultRest:45,  muscles:'Quads, glutes, calves, cardiovascular',     notes:'Squat to parallel, explode up, land softly with bent knees. Absorb the landing slowly to protect knees.'},
  {id:'e88', name:'Box Jumps',             category:'cardio',    movementPattern:'squat',     equipment:'other',   defaultSets:3, defaultReps:8,  defaultRest:60,  muscles:'Quads, glutes, calves, explosive power',    notes:'Jump up onto a sturdy box, land softly on both feet. Step down — never jump down. Build height progressively.'},
  {id:'e89', name:'Skipping',              category:'cardio',    movementPattern:'isometric', equipment:'other',   defaultSets:3, trackingType:'time', defaultDuration:60, defaultRest:60, muscles:'Calves, cardiovascular, coordination',      notes:'Land on balls of feet, small jumps. Wrists do the turning, not arms. Build from 30s to 3 minute rounds.'},
]

export default DEFAULT_EXERCISES
